build:
	@go build -o bin/HB02-2025_braindancers/backend cmd/main.go

run:
	@./bin/HB02-2025_braindancers/backend

test-integration:
	@go test -v ./tests/integration/...

test-unit:
	@go test -v ./tests/unit/...

test-all:
	@go test -v ./tests/...